gchqnet/accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("accounts/login/", views.LoginLandingView.as_view(), name="login"),
    path("accounts/login/badge/", views.BadgeLoginLandingView.as_view(), name="login_badge"),
    path(
        "accounts/login/badge/step-1/",
        views.BadgeLoginUsernamePromptView.as_view(),
        name="login_badge_username",
    ),
    path(
        "accounts/login/badge/step-2/",
        views.BadgeLoginChallengePromptView.as_view(),
        name="login_badge_challenge",
    ),
    path(
        "accounts/login/credentials/",
        views.CredentialsLoginView.as_view(),
        name="login_credentials",
    ),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("profile/settings/", views.AccountSettingsView.as_view(), name="settings"),
]

gchqnet/content/urls.py
from django.conf import settings
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "content"

urlpatterns = [
    path("about/", views.AboutPage.as_view(), name="about"),
    path("contact/", views.ContactPage.as_view(), name="contact"),
    path("holding/", views.HoldingPage.as_view(), name="holding"),
    path("platforms/", views.PlatformsPage.as_view(), name="platforms"),
    path("play/", views.PlayPage.as_view(), name="play"),
]

if settings.DEBUG:
    urlpatterns += [
        path("400/", TemplateView.as_view(template_name="400.html")),
        path("403/", TemplateView.as_view(template_name="403.html")),
        path("404/", TemplateView.as_view(template_name="404.html")),
        path("500/", TemplateView.as_view(template_name="500.html")),
    ]

gchqnet/core/urls.py
import notifications.urls
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("gchqnet.accounts.urls", namespace="accounts")),
    path("", include("gchqnet.achievements.urls", namespace="achievements")),
    path("", include("gchqnet.content.urls", namespace="content")),
    path("", include("gchqnet.quest.urls", namespace="quest")),
    path("", include("django_prometheus.urls")),
    path("admin/", admin.site.urls),
    path("api/", include("gchqnet.core.api", namespace="api")),
    path("ht/", include("health_check.urls")),
    path("logistics/", include("gchqnet.logistics.urls", namespace="logistics")),
    path("notifications/", include(notifications.urls, namespace="notifications")),
]

if apps.is_installed("debug_toolbar"):
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # type: ignore

gchqnet/logistics/urls.py
from django.urls import path

from . import views

app_name = "logistics"

urlpatterns = [
    path("", views.LogisticsHomeView.as_view(), name="home"),
    path("locations/", views.LocationsListView.as_view(), name="locations_list"),
    path("locations/map/", views.LocationMapView.as_view(), name="locations_map"),
    path("locations/<uuid:pk>/", views.LocationEditView.as_view(), name="locations_edit"),
    path("planned-locations/", views.PlannedLocationsListView.as_view(), name="planned_list"),
    path("planned-locations/map/", views.PlannedLocationMapView.as_view(), name="planned_map"),
    path("planned-locations/create/", views.PlannedLocationCreateView.as_view(), name="planned_create"),
    path("planned-locations/<uuid:pk>/", views.PlannedLocationEditView.as_view(), name="planned_edit"),
    path("planned-locations/<uuid:pk>/delete/", views.PlannedLocationDeleteView.as_view(), name="planned_delete"),
    path("planned-locations/<uuid:pk>/deploy/", views.PlannedLocationDeployView.as_view(), name="planned_deploy"),
]

gchqnet/quest/urls.py
from django.urls import path

from . import views

app_name = "quest"

urlpatterns = [
    path("", views.HomepageView.as_view(), name="home"),
    path("global-scoreboard/", views.GlobalScoreboardView.as_view(), name="global-scoreboard"),
    path("recent-activity/", views.GlobalRecentActivityView.as_view(), name="recent_activity"),
    path("leaderboards/", views.LeaderboardListView.as_view(), name="leaderboard_list"),
    path("leaderboards/create/", views.LeaderboardCreateView.as_view(), name="leaderboard_create"),
    path(
        "leaderboards/invite/<str:invite_code>/", views.LeaderboardInviteDetailView.as_view(), name="leaderboard_invite"
    ),
    path("leaderboards/<uuid:pk>/", views.LeaderboardDetailView.as_view(), name="leaderboard_detail"),
    path(
        "leaderboards/<uuid:pk>/activity/",
        views.LeaderboardDetailActivityView.as_view(),
        name="leaderboard_detail_activity",
    ),
    path(
        "leaderboards/<uuid:pk>/settings/",
        views.LeaderboardDetailSettingsView.as_view(),
        name="leaderboard_detail_settings",
    ),
    path("locations/<uuid:pk>/", views.LocationDetailView.as_view(), name="location_detail"),
    path("profile/", views.PlayerFindsView.as_view(), name="profile", kwargs={"current_user": True}),
    path(
        "profile/achievements/",
        views.PlayerAchievementsView.as_view(),
        name="profile_achievements",
        kwargs={"current_user": True},
    ),
    path(
        "profile/recent-activity/",
        views.PlayerRecentActivityView.as_view(),
        name="profile_activity",
        kwargs={"current_user": True},
    ),
    path(
        "profile/to-find/",
        views.MyProfileUnfoundLocationsView.as_view(),
        name="profile_to_find",
    ),
    path("map/", views.MapView.as_view(), name="map"),
    path(
        "players/<str:username>/", views.PlayerFindsView.as_view(), name="player_detail", kwargs={"current_user": False}
    ),
    path(
        "players/<str:username>/achievements/",
        views.PlayerAchievementsView.as_view(),
        name="player_achievements",
        kwargs={"current_user": False},
    ),
    path(
        "players/<str:username>/recent-activity/",
        views.PlayerRecentActivityView.as_view(),
        name="player_activity",
        kwargs={"current_user": False},
    ),
]

gchqnet/accounts/api/views.py
from django.conf import settings
from drf_spectacular.utils import extend_schema
from rest_framework import exceptions
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.request import Request
from rest_framework.response import Response

from gchqnet.accounts.models.user import User
from gchqnet.accounts.totp import CustomTOTP

from .serializers import (
    UserProfileSerializer,
    UserTokenRequestSerializer,
    UserTokenSerializer,
)


@extend_schema(summary="Get current user", responses=UserProfileSerializer, tags=["Users"])
@api_view(["GET"])
@permission_classes([IsAuthenticated])
def profile(request: Request) -> Response:
    serializer = UserProfileSerializer(
        instance=request.user,
        context={"request": request},
    )
    return Response(serializer.data)


@extend_schema(
    summary="Get API token",
    exclude=settings.HIDE_PRIVATE_API_ENDPOINTS,
    request=UserTokenRequestSerializer,
    responses={200: UserTokenSerializer},
    tags=["Users"],
)
@permission_classes([AllowAny])
@api_view(["POST"])
def get_auth_token(request: Request) -> Response:
    serializer = UserTokenRequestSerializer(data=request.data)
    serializer.is_valid(raise_exception=True)

    try:
        user = User.objects.prefetch_related("badges").get(
            username=serializer.validated_data["username"],
            is_active=True,
        )
    except User.DoesNotExist:
        raise exceptions.AuthenticationFailed() from None

    if "otp" in serializer.validated_data:
        security_code = serializer.validated_data["otp"]
        is_valid = any(
            CustomTOTP(mac_address).verify(security_code, valid_window=1)
            for mac_address in user.badges.values_list("mac_address", flat=True)
        )

        if not is_valid or user.is_superuser:
            raise exceptions.AuthenticationFailed()
    else:
        # Password Auth
        if not user.check_password(serializer.validated_data["password"]):
            raise exceptions.AuthenticationFailed()

    # For now, return the static token that every user has.
    response = UserTokenSerializer(
        instance=user,
        context={"request": request},
    )
    return Response(response.data)

gchqnet/accounts/views.py
from __future__ import annotations

from typing import TYPE_CHECKING, Any

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as DjangoLoginView
from django.contrib.auth.views import RedirectURLMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, resolve_url
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, TemplateView, UpdateView
from django_prometheus.conf import NAMESPACE
from prometheus_client import Counter

from gchqnet.accounts.mixins import LoginPageMixin
from gchqnet.achievements.repository import award_builtin_basic_achievement
from gchqnet.core.mixins import BreadcrumbsMixin

from .forms import (
    BadgeLoginChallengeForm,
    BadgeLoginUsernameForm,
    BaseAccountSettingsForm,
    CredentialsLoginForm,
    PasswordAccountSettingsForm,
    TOTPAccountSettingsForm,
)
from .models import User

if TYPE_CHECKING:  # pragma: nocover
    from django.db.models import QuerySet


logins_counter = Counter(
    "gchqnet_account_logins_total",
    "Number of user logins by method.",
    ["method"],
    namespace=NAMESPACE,
)


class AccountSettingsView(LoginRequiredMixin, BreadcrumbsMixin, UpdateView):
    template_name = "pages/accounts/settings.html"
    model = User
    form_class = PasswordAccountSettingsForm
    success_url = reverse_lazy("accounts:settings")
    breadcrumbs = [(None, "Settings")]

    def get_form_class(self) -> type[BaseAccountSettingsForm]:
        if self.object.password and self.object.has_usable_password():
            return PasswordAccountSettingsForm
        else:
            return TOTPAccountSettingsForm

    def get_object(self, queryset: QuerySet[User] | None = None) -> User:
        assert self.request.user.is_authenticated
        return self.request.user

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.object
        return kwargs

    def form_valid(self, form: BaseAccountSettingsForm) -> HttpResponse:
        self.object = form.save()

        if form.cleaned_data.get("new_password2"):
            messages.success(self.request, "Your password has been changed.")
            # Award Crypt Keeper
            award_builtin_basic_achievement("a3db72f7-6f7a-4f27-8996-ae1006df4b0d", self.object)

            # Cycle sessions if password has changed
            update_session_auth_hash(self.request, self.object)
        else:
            messages.success(self.request, "Updated account successfully.")

            # Award Identity Upgrade
            award_builtin_basic_achievement("a5927f71-f60a-4d7b-9abe-7427bf617dac", self.object)
        return redirect(self.get_success_url())

    def get_context_data(self, **kwargs: Any) -> dict[Any, Any]:
        assert self.request.user.is_authenticated
        return super().get_context_data(
            badges=self.request.user.badges.all(),
            **kwargs,
        )


class LoginLandingView(LoginPageMixin, BreadcrumbsMixin, TemplateView):
    template_name = "pages/accounts/login_landing.html"
    breadcrumbs = [(None, "Login to GCHQ.NET")]


class CredentialsLoginView(LoginPageMixin, BreadcrumbsMixin, DjangoLoginView):
    template_name = "pages/accounts/login_credentials.html"
    form_class = CredentialsLoginForm
    breadcrumbs = [(reverse_lazy("accounts:login"), "Login to GCHQ.NET"), (None, "Login using your password")]

    def form_valid(self, form: AuthenticationForm) -> HttpResponse:
        logins_counter.labels("password").inc()
        return super().form_valid(form)


class BadgeLoginLandingView(LoginPageMixin, BreadcrumbsMixin, TemplateView):
    template_name = "pages/accounts/login_badge_landing.html"
    breadcrumbs = [(reverse_lazy("accounts:login"), "Login to GCHQ.NET"), (None, "Login using your badge")]


class BadgeLoginUsernamePromptView(LoginPageMixin, BreadcrumbsMixin, FormView):
    template_name = "pages/accounts/login_badge_username.html"
    form_class = BadgeLoginUsernameForm
    success_url = reverse_lazy("accounts:login_badge_challenge")
    breadcrumbs = [(reverse_lazy("accounts:login"), "Login to GCHQ.NET"), (None, "Login using your badge")]

    def form_valid(self, form: BadgeLoginUsernameForm) -> HttpResponse:
        self.request.session["badge_login__user_id"] = form.cleaned_data["account_name"].id
        resp = super().form_valid(form)
        if next_q := self.request.GET.get("next"):
            resp["Location"] += f"?next={next_q}"
        return resp


class BadgeLoginChallengePromptView(LoginPageMixin, RedirectURLMixin, BreadcrumbsMixin, FormView):
    template_name = "pages/accounts/login_badge_challenge.html"
    form_class = BadgeLoginChallengeForm
    breadcrumbs = [(reverse_lazy("accounts:login"), "Login to GCHQ.NET"), (None, "Login using your badge")]

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if "badge_login__user_id" not in request.session:
            return redirect("accounts:login_badge")
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()

        # We might see a 500 here sometimes, but that's okay.
        user_id = self.request.session.get("badge_login__user_id", -1)
        kwargs["user"] = User.objects.get(id=user_id, is_active=True)
        return kwargs

    def form_valid(self, form: BadgeLoginChallengeForm) -> HttpResponse:
        del self.request.session["badge_login__user_id"]
        if form.user.is_superuser:
            messages.info(self.request, "Please login with a password for security purposes.")
            return redirect("accounts:login_credentials")
        else:
            # Award beyond the badge
            award_builtin_basic_achievement("145047b2-697b-4ce9-9f2d-b3ef03c2e507", form.user)
            logins_counter.labels("otp").inc()
            auth_login(self.request, form.user)
            return super().form_valid(form)

    def get_default_redirect_url(self) -> str:
        """Return the default redirect URL."""
        if self.next_page:
            return resolve_url(self.next_page)
        else:
            return resolve_url(settings.LOGIN_REDIRECT_URL)

gchqnet/content/views.py
from django.views.generic import TemplateView

from gchqnet.core.mixins import BreadcrumbsMixin


class AboutPage(BreadcrumbsMixin, TemplateView):
    template_name = "pages/content/about.html"
    breadcrumbs = [(None, "About GCHQ.NET")]


class ContactPage(BreadcrumbsMixin, TemplateView):
    template_name = "pages/content/contact.html"
    breadcrumbs = [(None, "Contact Us")]
    extra_context = {"dect_number": "4247", "fax_number": "2999"}


class PlayPage(BreadcrumbsMixin, TemplateView):
    template_name = "pages/content/play.html"
    breadcrumbs = [(None, "How to Play")]


class PlatformsPage(BreadcrumbsMixin, TemplateView):
    template_name = "pages/content/platforms.html"
    breadcrumbs = [(None, "Our Platforms")]


class HoldingPage(TemplateView):
    template_name = "pages/content/holding.html"

gchqnet/hexpansion/api/views.py
from django.conf import settings
from drf_spectacular.utils import extend_schema, extend_schema_view
from rest_framework import mixins, permissions, serializers, viewsets

from gchqnet.hexpansion.api.serializers import HexpansionSerializer
from gchqnet.hexpansion.models import Hexpansion


@extend_schema_view(
    retrieve=extend_schema(
        summary="Get a hexpansion", exclude=settings.HIDE_PRIVATE_API_ENDPOINTS, tags=["Hexpansions"]
    ),
    list=extend_schema(
        summary="Get a list of hexpansions", exclude=settings.HIDE_PRIVATE_API_ENDPOINTS, tags=["Hexpansions"]
    ),
    create=extend_schema(
        summary="Create a new hexpansion", exclude=settings.HIDE_PRIVATE_API_ENDPOINTS, tags=["Hexpansions"]
    ),
)
class HexpansionViewset(
    mixins.CreateModelMixin, mixins.RetrieveModelMixin, mixins.ListModelMixin, viewsets.GenericViewSet
):
    queryset = Hexpansion.objects.all()
    serializer_class = HexpansionSerializer
    permission_classes = [permissions.IsAdminUser]

    def perform_create(self, serializer: serializers.BaseSerializer) -> None:
        assert self.request.user.is_authenticated
        serializer.save(created_by=self.request.user)

gchqnet/templates/pages/logistics/planned_locations/create.html
{% extends "layouts/base_app.html" %}
{% load crispy_forms_tags %}

{% block title %}Create planned location{% endblock %}

{% block content %}
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      {% crispy form %}
    </div>
  </div>
{% endblock %}

gchqnet/templates/pages/logistics/planned_locations/delete.html
{% extends "layouts/base_app.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ object }}{% endblock %}

{% block content %}
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <p class="govuk-body">Please confirm that you wish to delete the planned location.</p>
      {% crispy form %}
    </div>
  </div>
{% endblock %}

gchqnet/templates/pages/logistics/planned_locations/deploy.html
{% extends "layouts/base_app.html" %}
{% load crispy_forms_tags location_tags static %}

{% block title %}Deploy {{ object }}{% endblock %}

{% block action_buttons %}
  <a class="govuk-button govuk-button--secondary gchqnet-page-header-actions__action" data-module="govuk-button" href="{% url 'logistics:planned_edit' object.id %}">
    Edit
  </a>
{% endblock %}

{% block content %}
  <link rel="stylesheet" href="{% static 'map/map.css' %}">
  <script src="{% static 'map/map.js' %}"></script>
  <div style="height: 400px; margin-bottom: 3em;">
    <noscript>You need Javascript enabled to view this map.</noscript>
    <div
      id="map"
      data-marker-form="true"
      data-marker-lat="id_lat"
      data-marker-long="id_long"
      data-location-geo-endpoint="{% url 'api:locations_all-geojson' %}"
      style="height: 400px;"
    ></div>
  </div>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <h2 class="govuk-heading-m">Location Details</h2>
      <dl class="govuk-summary-list">
        <div class="govuk-summary-list__row">
          <dt class="govuk-summary-list__key">
            Display name
          </dt>
          <dd class="govuk-summary-list__value">
            {{ object.display_name }}
          </dd>
        </div>
        <div class="govuk-summary-list__row">
          <dt class="govuk-summary-list__key">
            Internal name
          </dt>
          <dd class="govuk-summary-list__value">
            {{ object.internal_name }}
          </dd>
        </div>
        <div class="govuk-summary-list__row">
          <dt class="govuk-summary-list__key">
            Hint
          </dt>
          <dd class="govuk-summary-list__value">
            {{ object.hint }}
          </dd>
        </div>
        <div class="govuk-summary-list__row">
          <dt class="govuk-summary-list__key">
            Difficulty
          </dt>
          <dd class="govuk-summary-list__value">
            {% difficulty_tag object.difficulty %}
          </dd>
        </div>
      </dl>
      <h2 class="govuk-heading-m">Confirm deployment</h2>
      <p class="govuk-body">Please check the location on the map above and then fill out the form below.</p>
      {% crispy form %}
    </div>
  </div>
{% endblock %}

gchqnet/templates/pages/logistics/planned_locations/edit.html
{% extends "layouts/base_app.html" %}
{% load crispy_forms_tags static %}

{% block title %}{{ object }}{% endblock %}

{% block action_buttons %}
  <div class="govuk-button-group gchqnet-page-header-actions__action">
    {% if object.is_ready_to_deploy %}
      <a class="govuk-button" data-module="govuk-button" href="{% url 'logistics:planned_deploy' object.id %}">
        Deploy
      </a>
    {% endif %}
    <a class="govuk-button govuk-button--warning gchqnet-page-header-actions__action" data-module="govuk-button" href="{% url 'logistics:planned_delete' object.id %}">
      Delete
    </a>
  </div>
{% endblock %}

{% block content %}
  <link rel="stylesheet" href="{% static 'map/map.css' %}">
  <script src="{% static 'map/map.js' %}"></script>
  <div style="height: 400px; margin-bottom: 3em;">
    <noscript>You need Javascript enabled to view this map.</noscript>
    <div
      id="map"
      data-marker-form="true"
      data-marker-lat="id_lat"
      data-marker-long="id_long"
      data-location-geo-endpoint="{% url 'api:planned_locations-geojson' %}{% if object.id %}?exclude={{ object.id }}{% endif %}"
      style="height: 400px;"
    ></div>
  </div>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      {% crispy form %}
    </div>
  </div>
{% endblock %}

gchqnet/templates/pages/logistics/planned_locations/list.html
{% extends "layouts/base_app.html" %}

{% block title %}Planned Locations{% endblock %}

{% block action_buttons %}
    <div class="govuk-button-group gchqnet-page-header-actions__action">
        <a class="govuk-button" data-module="govuk-button" href="{% url 'logistics:planned_create' %}">
            New Planned Location
        </a>
        <a class="govuk-button" data-module="govuk-button" href="{% url 'logistics:planned_map' %}">
            View Map
        </a>
    </div>

{% endblock %}

{% block content %}
    <p class="govuk-body">The following locations have been planned. God forbid you deploy them.</p>
    {% include "components/logistics/planned-location-search.html" %}
    {% include "components/logistics/planned-locations-table.html" with planned_locations=page_obj %}
    {% if page_obj %}
        {% include "components/govuk/pagination.html" with extra_classes="gchqnet-pagination--center" %}
    {% else %}
        <p class="govuk-body">There are no planned locations. Maybe we deployed them? Maybe we are useless?</p>
    {% endif %}
{% endblock %}

gchqnet/templates/pages/logistics/planned_locations/map.html
{% extends "layouts/base_app.html" %}
{% load static %}

{% block title %}Map{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'map/map.css' %}">
    <script src="{% static 'map/map.js' %}" style="max-width: 300px;"></script>
    <noscript>You need Javascript enabled to view this map.</noscript>

    <p class="govuk-body">
        This is a map of planned locations.
    </p>

    <div id="map" data-urlhash data-location-geo-endpoint="{% url 'api:planned_locations-geojson' %}" style="min-height: 800px;"></div>
{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'map/map.css' %}">
{% endblock %}

{% block js %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'map/map.js' %}">
{% endblock %}