gchqnet/accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("accounts/login/", views.LoginLandingView.as_view(), name="login"),
    path("accounts/login/badge/", views.BadgeLoginLandingView.as_view(), name="login_badge"),
    path(
        "accounts/login/badge/step-1/",
        views.BadgeLoginUsernamePromptView.as_view(),
        name="login_badge_username",
    ),
    path(
        "accounts/login/badge/step-2/",
        views.BadgeLoginChallengePromptView.as_view(),
        name="login_badge_challenge",
    ),
    path(
        "accounts/login/credentials/",
        views.CredentialsLoginView.as_view(),
        name="login_credentials",
    ),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("profile/settings/", views.AccountSettingsView.as_view(), name="settings"),
]

gchqnet/content/urls.py
from django.conf import settings
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "content"

urlpatterns = [
    path("about/", views.AboutPage.as_view(), name="about"),
    path("contact/", views.ContactPage.as_view(), name="contact"),
    path("holding/", views.HoldingPage.as_view(), name="holding"),
    path("platforms/", views.PlatformsPage.as_view(), name="platforms"),
    path("play/", views.PlayPage.as_view(), name="play"),
]

if settings.DEBUG:
    urlpatterns += [
        path("400/", TemplateView.as_view(template_name="400.html")),
        path("403/", TemplateView.as_view(template_name="403.html")),
        path("404/", TemplateView.as_view(template_name="404.html")),
        path("500/", TemplateView.as_view(template_name="500.html")),
    ]

gchqnet/core/urls.py
import notifications.urls
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("gchqnet.accounts.urls", namespace="accounts")),
    path("", include("gchqnet.achievements.urls", namespace="achievements")),
    path("", include("gchqnet.content.urls", namespace="content")),
    path("", include("gchqnet.quest.urls", namespace="quest")),
    path("", include("django_prometheus.urls")),
    path("admin/", admin.site.urls),
    path("api/", include("gchqnet.core.api", namespace="api")),
    path("ht/", include("health_check.urls")),
    path("logistics/", include("gchqnet.logistics.urls", namespace="logistics")),
    path("notifications/", include(notifications.urls, namespace="notifications")),
]

if apps.is_installed("debug_toolbar"):
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # type: ignore

gchqnet/quest/urls.py
from django.urls import path

from . import views

app_name = "quest"

urlpatterns = [
    path("", views.HomepageView.as_view(), name="home"),
    path("global-scoreboard/", views.GlobalScoreboardView.as_view(), name="global-scoreboard"),
    path("recent-activity/", views.GlobalRecentActivityView.as_view(), name="recent_activity"),
    path("leaderboards/", views.LeaderboardListView.as_view(), name="leaderboard_list"),
    path("leaderboards/create/", views.LeaderboardCreateView.as_view(), name="leaderboard_create"),
    path(
        "leaderboards/invite/<str:invite_code>/", views.LeaderboardInviteDetailView.as_view(), name="leaderboard_invite"
    ),
    path("leaderboards/<uuid:pk>/", views.LeaderboardDetailView.as_view(), name="leaderboard_detail"),
    path(
        "leaderboards/<uuid:pk>/activity/",
        views.LeaderboardDetailActivityView.as_view(),
        name="leaderboard_detail_activity",
    ),
    path(
        "leaderboards/<uuid:pk>/settings/",
        views.LeaderboardDetailSettingsView.as_view(),
        name="leaderboard_detail_settings",
    ),
    path("locations/<uuid:pk>/", views.LocationDetailView.as_view(), name="location_detail"),
    path("profile/", views.PlayerFindsView.as_view(), name="profile", kwargs={"current_user": True}),
    path(
        "profile/achievements/",
        views.PlayerAchievementsView.as_view(),
        name="profile_achievements",
        kwargs={"current_user": True},
    ),
    path(
        "profile/recent-activity/",
        views.PlayerRecentActivityView.as_view(),
        name="profile_activity",
        kwargs={"current_user": True},
    ),
    path(
        "profile/to-find/",
        views.MyProfileUnfoundLocationsView.as_view(),
        name="profile_to_find",
    ),
    path("map/", views.MapView.as_view(), name="map"),
    path(
        "players/<str:username>/", views.PlayerFindsView.as_view(), name="player_detail", kwargs={"current_user": False}
    ),
    path(
        "players/<str:username>/achievements/",
        views.PlayerAchievementsView.as_view(),
        name="player_achievements",
        kwargs={"current_user": False},
    ),
    path(
        "players/<str:username>/recent-activity/",
        views.PlayerRecentActivityView.as_view(),
        name="player_activity",
        kwargs={"current_user": False},
    ),
]

gchqnet/accounts/api/views.py
from django.conf import settings
from drf_spectacular.utils import extend_schema
from rest_framework import exceptions
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.request import Request
from rest_framework.response import Response

from gchqnet.accounts.models.user import User
from gchqnet.accounts.totp import CustomTOTP

from .serializers import (
    UserProfileSerializer,
    UserTokenRequestSerializer,
    UserTokenSerializer,
)


@extend_schema(summary="Get current user", responses=UserProfileSerializer, tags=["Users"])
@api_view(["GET"])
@permission_classes([IsAuthenticated])
def profile(request: Request) -> Response:
    serializer = UserProfileSerializer(
        instance=request.user,
        context={"request": request},
    )
    return Response(serializer.data)


@extend_schema(
    summary="Get API token",
    exclude=settings.HIDE_PRIVATE_API_ENDPOINTS,
    request=UserTokenRequestSerializer,
    responses={200: UserTokenSerializer},
    tags=["Users"],
)
@permission_classes([AllowAny])
@api_view(["POST"])
def get_auth_token(request: Request) -> Response:
    serializer = UserTokenRequestSerializer(data=request.data)
    serializer.is_valid(raise_exception=True)

    try:
        user = User.objects.prefetch_related("badges").get(
            username=serializer.validated_data["username"],
            is_active=True,
        )
    except User.DoesNotExist:
        raise exceptions.AuthenticationFailed() from None

    if "otp" in serializer.validated_data:
        security_code = serializer.validated_data["otp"]
        is_valid = any(
            CustomTOTP(mac_address).verify(security_code, valid_window=1)
            for mac_address in user.badges.values_list("mac_address", flat=True)
        )

        if not is_valid or user.is_superuser:
            raise exceptions.AuthenticationFailed()
    else:
        # Password Auth
        if not user.check_password(serializer.validated_data["password"]):
            raise exceptions.AuthenticationFailed()

    # For now, return the static token that every user has.
    response = UserTokenSerializer(
        instance=user,
        context={"request": request},
    )
    return Response(response.data)

gchqnet/accounts/views.py
from __future__ import annotations

from typing import TYPE_CHECKING, Any

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as DjangoLoginView
from django.contrib.auth.views import RedirectURLMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, resolve_url
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, TemplateView, UpdateView
from django_prometheus.conf import NAMESPACE
from prometheus_client import Counter

from gchqnet.accounts.mixins import LoginPageMixin
from gchqnet.achievements.repository import award_builtin_basic_achievement
from gchqnet.core.mixins import BreadcrumbsMixin

from .forms import (
    BadgeLoginChallengeForm,
    BadgeLoginUsernameForm,
    BaseAccountSettingsForm,
    CredentialsLoginForm,
    PasswordAccountSettingsForm,
    TOTPAccountSettingsForm,
)
from .models import User

if TYPE_CHECKING:  # pragma: nocover
    from django.db.models import QuerySet


logins_counter = Counter(
    "gchqnet_account_logins_total",
    "Number of user logins by method.",
    ["method"],
    namespace=NAMESPACE,
)


class AccountSettingsView(LoginRequiredMixin, BreadcrumbsMixin, UpdateView):
    template_name = "pages/accounts/settings.html"
    model = User
    form_class = PasswordAccountSettingsForm
    success_url = reverse_lazy("accounts:settings")
    breadcrumbs = [(None, "Settings")]

    def get_form_class(self) -> type[BaseAccountSettingsForm]:
        if self.object.password and self.object.has_usable_password():
            return PasswordAccountSettingsForm
        else:
            return TOTPAccountSettingsForm

    def get_object(self, queryset: QuerySet[User] | None = None) -> User:
        assert self.request.user.is_authenticated
        return self.request.user

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.object
        return kwargs

    def form_valid(self, form: BaseAccountSettingsForm) -> HttpResponse:
        self.object = form.save()

        if form.cleaned_data.get("new_password2"):
            messages.success(self.request, "Your password has been changed.")
            # Award Crypt Keeper
            award_builtin_basic_achievement("a3db72f7-6f7a-4f27-8996-ae1006df4b0d", self.object)

            # Cycle sessions if password has changed
            update_session_auth_hash(self.request, self.object)
        else:
            messages.success(self.request, "Updated account successfully.")

            # Award Identity Upgrade
            award_builtin_basic_achievement("a5927f71-f60a-4d7b-9abe-7427bf617dac", self.object)
        return redirect(self.get_success_url())

    def get_context_data(self, **kwargs: Any) -> dict[Any, Any]:
        assert self.request.user.is_authenticated
        return super().get_context_data(
            badges=self.request.user.badges.all(),
            **kwargs,
        )


class LoginLandingView(LoginPageMixin, BreadcrumbsMixin, TemplateView):
    template_name = "pages/accounts/login_landing.html"
    breadcrumbs = [(None, "Login to GCHQ.NET")]


class CredentialsLoginView(LoginPageMixin, BreadcrumbsMixin, DjangoLoginView):
    template_name = "pages/accounts/login_credentials.html"
    form_class = CredentialsLoginForm
    breadcrumbs = [(reverse_lazy("accounts:login"), "Login to GCHQ.NET"), (None, "Login using your password")]

    def form_valid(self, form: AuthenticationForm) -> HttpResponse:
        logins_counter.labels("password").inc()
        return super().form_valid(form)


class BadgeLoginLandingView(LoginPageMixin, BreadcrumbsMixin, TemplateView):
    template_name = "pages/accounts/login_badge_landing.html"
    breadcrumbs = [(reverse_lazy("accounts:login"), "Login to GCHQ.NET"), (None, "Login using your badge")]


class BadgeLoginUsernamePromptView(LoginPageMixin, BreadcrumbsMixin, FormView):
    template_name = "pages/accounts/login_badge_username.html"
    form_class = BadgeLoginUsernameForm
    success_url = reverse_lazy("accounts:login_badge_challenge")
    breadcrumbs = [(reverse_lazy("accounts:login"), "Login to GCHQ.NET"), (None, "Login using your badge")]

    def form_valid(self, form: BadgeLoginUsernameForm) -> HttpResponse:
        self.request.session["badge_login__user_id"] = form.cleaned_data["account_name"].id
        resp = super().form_valid(form)
        if next_q := self.request.GET.get("next"):
            resp["Location"] += f"?next={next_q}"
        return resp


class BadgeLoginChallengePromptView(LoginPageMixin, RedirectURLMixin, BreadcrumbsMixin, FormView):
    template_name = "pages/accounts/login_badge_challenge.html"
    form_class = BadgeLoginChallengeForm
    breadcrumbs = [(reverse_lazy("accounts:login"), "Login to GCHQ.NET"), (None, "Login using your badge")]

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if "badge_login__user_id" not in request.session:
            return redirect("accounts:login_badge")
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()

        # We might see a 500 here sometimes, but that's okay.
        user_id = self.request.session.get("badge_login__user_id", -1)
        kwargs["user"] = User.objects.get(id=user_id, is_active=True)
        return kwargs

    def form_valid(self, form: BadgeLoginChallengeForm) -> HttpResponse:
        del self.request.session["badge_login__user_id"]
        if form.user.is_superuser:
            messages.info(self.request, "Please login with a password for security purposes.")
            return redirect("accounts:login_credentials")
        else:
            # Award beyond the badge
            award_builtin_basic_achievement("145047b2-697b-4ce9-9f2d-b3ef03c2e507", form.user)
            logins_counter.labels("otp").inc()
            auth_login(self.request, form.user)
            return super().form_valid(form)

    def get_default_redirect_url(self) -> str:
        """Return the default redirect URL."""
        if self.next_page:
            return resolve_url(self.next_page)
        else:
            return resolve_url(settings.LOGIN_REDIRECT_URL)

gchqnet/achievements/api/views.py
from uuid import UUID

from django.conf import settings
from django.core.signing import BadSignature, Signer
from django.shortcuts import get_object_or_404
from drf_spectacular.utils import extend_schema
from rest_framework import exceptions, permissions, serializers, viewsets
from rest_framework.decorators import action
from rest_framework.request import Request
from rest_framework.response import Response

from gchqnet.accounts.models.user import User
from gchqnet.achievements.models import BasicAchievement, BasicAchievementAwardType
from gchqnet.achievements.repository import award_builtin_basic_achievement

from .serializers import AchievementSubmissionSerializer


class AchievementViewset(viewsets.GenericViewSet):
    permission_classes = (permissions.AllowAny,)

    @extend_schema(
        summary="Submit an achievement gained on another server",
        exclude=settings.HIDE_PRIVATE_API_ENDPOINTS,
        request=AchievementSubmissionSerializer,
        responses={200: serializers.Serializer, 201: serializers.Serializer},
        tags=["Achievements"],
    )
    @action(methods=["POST"], detail=True)
    def submit(self, request: Request, pk: UUID) -> Response:
        serializer = AchievementSubmissionSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        achievement = get_object_or_404(BasicAchievement, pk=pk)

        if achievement.award_type != BasicAchievementAwardType.EXTERNAL:
            raise exceptions.ValidationError(
                detail={"detail": ["That achievement cannot be awarded using this endpoint."]}
            )

        signer = Signer()

        try:
            obj = signer.unsign_object(serializer.validated_data["token"])
        except BadSignature:
            raise exceptions.AuthenticationFailed() from None

        if str(achievement.id) != obj["ba"]:
            raise exceptions.ValidationError(detail={"detail": ["That token isn't allowed to award that achievement"]})

        try:
            user = User.objects.get(username=serializer.validated_data["username"])
        except User.DoesNotExist:
            raise exceptions.ValidationError(detail={"detail": ["That user cannot be found."]}) from None

        result = award_builtin_basic_achievement(achievement.id, user)

        resp_code_lut = {"success": 201, "already_obtained": 200, "failure": 500}

        return Response(status=resp_code_lut[result])

gchqnet/content/views.py
from django.views.generic import TemplateView

from gchqnet.core.mixins import BreadcrumbsMixin


class AboutPage(BreadcrumbsMixin, TemplateView):
    template_name = "pages/content/about.html"
    breadcrumbs = [(None, "About GCHQ.NET")]


class ContactPage(BreadcrumbsMixin, TemplateView):
    template_name = "pages/content/contact.html"
    breadcrumbs = [(None, "Contact Us")]
    extra_context = {"dect_number": "4247", "fax_number": "2999"}


class PlayPage(BreadcrumbsMixin, TemplateView):
    template_name = "pages/content/play.html"
    breadcrumbs = [(None, "How to Play")]


class PlatformsPage(BreadcrumbsMixin, TemplateView):
    template_name = "pages/content/platforms.html"
    breadcrumbs = [(None, "Our Platforms")]


class HoldingPage(TemplateView):
    template_name = "pages/content/holding.html"

gchqnet/templates/pages/accounts/finds.html
{% extends "layouts/base_app.html" %}

{% block title %}My Finds{% endblock %}

{% block content %}
  <div style="float: right;" class="govuk-checkboxes" data-module="govuk-checkboxes">
    <div class="govuk-checkboxes__item">
      <input class="govuk-checkboxes__input" id="hidemissing" name="hidemissing" type="checkbox">
      <label class="govuk-label govuk-checkboxes__label" for="hidemissing">
        Hide Missing
      </label>
    </div>
  </div>
  <div class="govuk-tabs" data-module="govuk-tabs">
    <h2 class="govuk-tabs__title">
      My Finds
    </h2>
    <table class="govuk-table govuk-table--small-text-until-tablet">
      <thead class="govuk-table__head">
        <tr class="govuk-table__row">
          <th scope="col" class="govuk-table__header">Name</th>
          <th scope="col" class="govuk-table__header">Difficulty</th>
          <th scope="col" class="govuk-table__header">Hints / Found At</th>
          <th scope="col" class="govuk-table__header"></th>
        </tr>
      </thead>
      <tbody class="govuk-table__body">
        {% for location, capture in finds.items %}
          {% if capture %}
            <tr class="govuk-table__row">
              <th scope="row" class="govuk-table__header">{{ location.display_name }}</th>
              <td class="govuk-colour__red govuk-table__cell">{{ location.difficulty }}</td>
              <td class="govuk-table__cell">{{ capture.raw_capture_event.created_at }}</td>
              <td class="govuk-table__cell"><a class="govuk-link" href="#">View</a></td>
          {% else %}
            <tr class="govuk-table__row quest-missing" bgcolor="#d3d3d3">
              <th scope="row" class="govuk-table__header">???</th>
              <td class="govuk-table__cell">{{ location.difficulty }}</td>
              <td class="govuk-table__cell">{{ location.hint }}</td>
              <td class="govuk-table__cell"><a class="govuk-link" href="#">View</a></td>
          {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <script>
    document.querySelector("#hidemissing").addEventListener("change", function() {
      var missing = document.querySelectorAll(".quest-missing");
      if (this.checked) {
        missing.forEach(function(element) {
          element.style.display = "none";
        });
      } else {
        missing.forEach(function(element) {
          element.style.display = "";
        });
      }
    });
  </script>
{% endblock %}

gchqnet/templates/pages/accounts/login_badge.html
{% extends "layouts/base_app.html" %}
{% load crispy_forms_tags %}

{% block title %}Login to GCHQ.NET{% endblock %}

{% block content %}
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <h1 class="govuk-heading-l">Login using your badge</h1>

      {% include 'components/govuk/notification-banner.html' with heading='This feature is not implemented yet.' %}
    </div>
  </div>

  <h2 class="govuk-heading-m">Other ways to login</h2>
  <p class="govuk-body">If you have set a password on your account, you can <a href="{% url 'accounts:login_credentials' %}{{ query_string}}">login using your password</a>.</p>
{% endblock %}

gchqnet/templates/pages/accounts/login_badge_challenge.html
{% extends "layouts/base_app.html" %}
{% load crispy_forms_tags %}

{% block title %}Login to GCHQ.NET{% endblock %}

{% block content %}
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <h1 class="govuk-heading-l">Please enter your security code</h1>
      <p class="govuk-body">We need to be able to verify you own your badge to be able to log you in.</p>
      <p class="govuk-body">Your security code is shown on the login page of the GCHQ.NET badge app.</p>
      <p class="govuk-body">Security codes will change every 30 seconds, so please make sure you enter it immediately.</p>
      {% crispy form %}
    </div>
  </div>

  <h2 class="govuk-heading-m">If you cannot login into your account</h2>
  <p class="govuk-body"><a href="{% url 'content:contact' %}">Contact our support team</a> if you cannot connect your badge or if your account has been duplicated.</p>

  <h2 class="govuk-heading-m">Other ways to login</h2>
  <p class="govuk-body">If you have set a password on your account, you can <a href="{% url 'accounts:login_credentials' %}{{ query_string }}">login using your password</a>.</p>
{% endblock %}

gchqnet/templates/pages/accounts/login_badge_landing.html
{% extends "layouts/base_app.html" %}

{% block title %}Login to GCHQ.NET{% endblock %}

{% block content %}
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <h1 class="govuk-heading-l">Get ready to login with your badge</h1>
      <p class="govuk-body">Let's get ready to login with your badge:</p>
      <ol class="govuk-list govuk-list--number">
        <li>Download the GCHQ.NET App to your badge</li>
        <li>Ensure that your badge is connected to Wi-Fi</li>
        <li>Open the GCHQ.NET App and select <strong>login</strong></li>
      </ol>
      <a class="govuk-button" href="{% url 'accounts:login_badge_username' %}{{ query_string }}">Continue</a>
    </div>
  </div>

  <h2 class="govuk-heading-m">If you cannot login into your account</h2>
  <p class="govuk-body"><a href="{% url 'content:contact' %}">Contact our support team</a> if you cannot connect your badge or if your account has been duplicated.</p>

  <h2 class="govuk-heading-m">Other ways to login</h2>
  <p class="govuk-body">If you have set a password on your account, you can <a href="{% url 'accounts:login_credentials' %}{{ query_string}}">login using your password</a>.</p>
{% endblock %}

gchqnet/templates/pages/accounts/login_badge_username.html
{% extends "layouts/base_app.html" %}
{% load crispy_forms_tags %}

{% block title %}Login to GCHQ.NET{% endblock %}

{% block content %}
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <h1 class="govuk-heading-l">Please enter your account name</h1>
      <p class="govuk-body">We need to be able to identify your badge before we can log you in.</p>
      <p class="govuk-body">Your account name is shown on the login page of the GCHQ.NET badge app.</p>
      {% crispy form %}
    </div>
  </div>

  <h2 class="govuk-heading-m">If you cannot login into your account</h2>
  <p class="govuk-body"><a href="{% url 'content:contact' %}">Contact our support team</a> if you cannot connect your badge or if your account has been duplicated.</p>

  <h2 class="govuk-heading-m">Other ways to login</h2>
  <p class="govuk-body">If you have set a password on your account, you can <a href="{% url 'accounts:login_credentials' %}{{ query_string}}">login using your password</a>.</p>
{% endblock %}

gchqnet/templates/pages/accounts/login_credentials.html
{% extends "layouts/base_app.html" %}
{% load crispy_forms_tags %}

{% block title %}Login to GCHQ.NET{% endblock %}

{% block content %}
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <h1 class="govuk-heading-l">Login using your password</h1>
      {% crispy form %}
    </div>
  </div>

  <h2 class="govuk-heading-m">Other ways to login</h2>
  <p class="govuk-body">If you have not set a password on your account, you can <a href="{% url 'accounts:login_badge' %}{{ query_string}}">login using your badge</a>.</p>
{% endblock %}

gchqnet/templates/pages/accounts/login_landing.html
{% extends "layouts/base_app.html" %}

{% block title %}Login to GCHQ.NET{% endblock %}

{% block content %}
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <h1 class="govuk-heading-l">Login to Great Camp Hexpansion Quest</h1>
      <p class="govuk-body">After authenticating using your badge, you can view all of your finds, achievements, hints and compete against your friends.</p>
      <p class="govuk-body">You will need:</p>
      <ul class="govuk-list govuk-list--bullet">
        <li>your EMF Tildagon badge</li>
        <li>the GCHQ.NET badge app</li>
      </ul>
      <div class="govuk-inset-text">
        This page is not yet available in Welsh.
      </div>
      <a href="{% url 'accounts:login_badge' %}{{ query_string }}" role="button" draggable="false" class="govuk-button govuk-button--start" data-module="govuk-button">
        Start now
        <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" aria-hidden="true" focusable="false">
          <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z" />
        </svg>
      </a>
    </div>
  </div>

  <h2 class="govuk-heading-m">If you cannot login into your account</h2>
  <p class="govuk-body"><a href="{% url 'content:contact' %}">Contact our support team</a> if you cannot connect your badge or if your account has been duplicated.</p>

  <h2 class="govuk-heading-m">Other ways to login</h2>
  <p class="govuk-body">If you have set a password on your account, you can <a href="{% url 'accounts:login_credentials' %}{{ query_string }}">login using a password</a>.</p>
{% endblock %}

gchqnet/templates/pages/accounts/profile.html
{% extends "layouts/base_app.html" %}
{% load crispy_forms_tags %}

{% block title %}My Profile{% endblock %}

{% block content %}
  <div class="govuk-tabs" data-module="govuk-tabs">
    <h2 class="govuk-tabs__title">
      My Profile
    </h2>
    <ul class="govuk-tabs__list">
      <li class="govuk-tabs__list-item govuk-tabs__list-item--selected">
        <a class="govuk-tabs__tab" href="#details">
          My details
        </a>
      </li>
      <li class="govuk-tabs__list-item">
        <a class="govuk-tabs__tab" href="#badges">
          My badges
        </a>
      </li>
      <li class="govuk-tabs__list-item">
        <a class="govuk-tabs__tab" href="#api">
          API Access
        </a>
      </li>
    </ul>
    <div class="govuk-tabs__panel" id="details">
      <h2 class="govuk-heading-l">My details</h2>
      <p class="govuk-body">You can update your profile details below:</p>
      {% crispy form %}
    </div>
    <div class="govuk-tabs__panel govuk-tabs__panel--hidden" id="badges">
      <h2 class="govuk-heading-l">My badges</h2>
      <p class="govuk-body">You have {{ badges|length }} badge{{ badges|pluralize }} connected to your account.</p>
      {% include "components/accounts/badge-list.html" with badges=badges %}
      <details class="govuk-details">
        <summary class="govuk-details__summary">
          <span class="govuk-details__summary-text">
            How to connect my badge?
          </span>
        </summary>
        <div class="govuk-details__text">
          You will need to contact an administrator to connect a badge to an existing account. Please get in touch and we'll be happy to help you.
        </div>
      </details>
    </div>
    <div class="govuk-tabs__panel govuk-tabs__panel--hidden" id="api">
      <h2 class="govuk-heading-l">API Access</h2>
      <p class="govuk-body">The GCHQ.NET API can be used to synergistically integrate the GCHQ.NET REST API Framework Platform System Cloud Service into your own projects.</p>
      <p class="govuk-body">Each user has one API token, which has full access to your account.</p>
      <div class="govuk-form-group">
        <label class="govuk-label" for="api-token">
          API Token
        </label>
        <input class="govuk-input govuk-!-width-three-quarters" id="api-token" name="api-token" type="text" value="{{ request.user.api_token }}" readonly>
        <button class="govuk-button" id="copy-api-token-button">
          Copy to clipboard
        </button>
      </div>
      <p class="govuk-body">There is <a href="{% url 'api:docs' %}">documentation available for the API endpoints</a>.</p>
      <script>
        var copyAPITokenButton = document.querySelector('#copy-api-token-button');

        copyAPITokenButton.addEventListener('click', function(event) {
          var copyAPITokenInput = document.querySelector('#api-token');
          copyAPITokenInput.select();
          copyAPITokenInput.setSelectionRange(0, 99999); // For mobile devices
          navigator.clipboard.writeText(copyAPITokenInput.value);
        });
      </script>
    </div>
  </div>
{% endblock %}