gchqnet/accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("accounts/login/", views.LoginLandingView.as_view(), name="login"),
    path("accounts/login/badge/", views.BadgeLoginLandingView.as_view(), name="login_badge"),
    path(
        "accounts/login/badge/step-1/",
        views.BadgeLoginUsernamePromptView.as_view(),
        name="login_badge_username",
    ),
    path(
        "accounts/login/badge/step-2/",
        views.BadgeLoginChallengePromptView.as_view(),
        name="login_badge_challenge",
    ),
    path(
        "accounts/login/credentials/",
        views.CredentialsLoginView.as_view(),
        name="login_credentials",
    ),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("profile/settings/", views.AccountSettingsView.as_view(), name="settings"),
]

gchqnet/content/urls.py
from django.conf import settings
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "content"

urlpatterns = [
    path("about/", views.AboutPage.as_view(), name="about"),
    path("contact/", views.ContactPage.as_view(), name="contact"),
    path("holding/", views.HoldingPage.as_view(), name="holding"),
    path("platforms/", views.PlatformsPage.as_view(), name="platforms"),
    path("play/", views.PlayPage.as_view(), name="play"),
]

if settings.DEBUG:
    urlpatterns += [
        path("400/", TemplateView.as_view(template_name="400.html")),
        path("403/", TemplateView.as_view(template_name="403.html")),
        path("404/", TemplateView.as_view(template_name="404.html")),
        path("500/", TemplateView.as_view(template_name="500.html")),
    ]

gchqnet/core/urls.py
import notifications.urls
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("gchqnet.accounts.urls", namespace="accounts")),
    path("", include("gchqnet.achievements.urls", namespace="achievements")),
    path("", include("gchqnet.content.urls", namespace="content")),
    path("", include("gchqnet.quest.urls", namespace="quest")),
    path("", include("django_prometheus.urls")),
    path("admin/", admin.site.urls),
    path("api/", include("gchqnet.core.api", namespace="api")),
    path("ht/", include("health_check.urls")),
    path("logistics/", include("gchqnet.logistics.urls", namespace="logistics")),
    path("notifications/", include(notifications.urls, namespace="notifications")),
]

if apps.is_installed("debug_toolbar"):
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # type: ignore

gchqnet/quest/urls.py
from django.urls import path

from . import views

app_name = "quest"

urlpatterns = [
    path("", views.HomepageView.as_view(), name="home"),
    path("global-scoreboard/", views.GlobalScoreboardView.as_view(), name="global-scoreboard"),
    path("recent-activity/", views.GlobalRecentActivityView.as_view(), name="recent_activity"),
    path("leaderboards/", views.LeaderboardListView.as_view(), name="leaderboard_list"),
    path("leaderboards/create/", views.LeaderboardCreateView.as_view(), name="leaderboard_create"),
    path(
        "leaderboards/invite/<str:invite_code>/", views.LeaderboardInviteDetailView.as_view(), name="leaderboard_invite"
    ),
    path("leaderboards/<uuid:pk>/", views.LeaderboardDetailView.as_view(), name="leaderboard_detail"),
    path(
        "leaderboards/<uuid:pk>/activity/",
        views.LeaderboardDetailActivityView.as_view(),
        name="leaderboard_detail_activity",
    ),
    path(
        "leaderboards/<uuid:pk>/settings/",
        views.LeaderboardDetailSettingsView.as_view(),
        name="leaderboard_detail_settings",
    ),
    path("locations/<uuid:pk>/", views.LocationDetailView.as_view(), name="location_detail"),
    path("profile/", views.PlayerFindsView.as_view(), name="profile", kwargs={"current_user": True}),
    path(
        "profile/achievements/",
        views.PlayerAchievementsView.as_view(),
        name="profile_achievements",
        kwargs={"current_user": True},
    ),
    path(
        "profile/recent-activity/",
        views.PlayerRecentActivityView.as_view(),
        name="profile_activity",
        kwargs={"current_user": True},
    ),
    path(
        "profile/to-find/",
        views.MyProfileUnfoundLocationsView.as_view(),
        name="profile_to_find",
    ),
    path("map/", views.MapView.as_view(), name="map"),
    path(
        "players/<str:username>/", views.PlayerFindsView.as_view(), name="player_detail", kwargs={"current_user": False}
    ),
    path(
        "players/<str:username>/achievements/",
        views.PlayerAchievementsView.as_view(),
        name="player_achievements",
        kwargs={"current_user": False},
    ),
    path(
        "players/<str:username>/recent-activity/",
        views.PlayerRecentActivityView.as_view(),
        name="player_activity",
        kwargs={"current_user": False},
    ),
]

gchqnet/accounts/api/views.py
from django.conf import settings
from drf_spectacular.utils import extend_schema
from rest_framework import exceptions
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.request import Request
from rest_framework.response import Response

from gchqnet.accounts.models.user import User
from gchqnet.accounts.totp import CustomTOTP

from .serializers import (
    UserProfileSerializer,
    UserTokenRequestSerializer,
    UserTokenSerializer,
)


@extend_schema(summary="Get current user", responses=UserProfileSerializer, tags=["Users"])
@api_view(["GET"])
@permission_classes([IsAuthenticated])
def profile(request: Request) -> Response:
    serializer = UserProfileSerializer(
        instance=request.user,
        context={"request": request},
    )
    return Response(serializer.data)


@extend_schema(
    summary="Get API token",
    exclude=settings.HIDE_PRIVATE_API_ENDPOINTS,
    request=UserTokenRequestSerializer,
    responses={200: UserTokenSerializer},
    tags=["Users"],
)
@permission_classes([AllowAny])
@api_view(["POST"])
def get_auth_token(request: Request) -> Response:
    serializer = UserTokenRequestSerializer(data=request.data)
    serializer.is_valid(raise_exception=True)

    try:
        user = User.objects.prefetch_related("badges").get(
            username=serializer.validated_data["username"],
            is_active=True,
        )
    except User.DoesNotExist:
        raise exceptions.AuthenticationFailed() from None

    if "otp" in serializer.validated_data:
        security_code = serializer.validated_data["otp"]
        is_valid = any(
            CustomTOTP(mac_address).verify(security_code, valid_window=1)
            for mac_address in user.badges.values_list("mac_address", flat=True)
        )

        if not is_valid or user.is_superuser:
            raise exceptions.AuthenticationFailed()
    else:
        # Password Auth
        if not user.check_password(serializer.validated_data["password"]):
            raise exceptions.AuthenticationFailed()

    # For now, return the static token that every user has.
    response = UserTokenSerializer(
        instance=user,
        context={"request": request},
    )
    return Response(response.data)

gchqnet/accounts/views.py
from __future__ import annotations

from typing import TYPE_CHECKING, Any

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as DjangoLoginView
from django.contrib.auth.views import RedirectURLMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, resolve_url
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, TemplateView, UpdateView
from django_prometheus.conf import NAMESPACE
from prometheus_client import Counter

from gchqnet.accounts.mixins import LoginPageMixin
from gchqnet.achievements.repository import award_builtin_basic_achievement
from gchqnet.core.mixins import BreadcrumbsMixin

from .forms import (
    BadgeLoginChallengeForm,
    BadgeLoginUsernameForm,
    BaseAccountSettingsForm,
    CredentialsLoginForm,
    PasswordAccountSettingsForm,
    TOTPAccountSettingsForm,
)
from .models import User

if TYPE_CHECKING:  # pragma: nocover
    from django.db.models import QuerySet


logins_counter = Counter(
    "gchqnet_account_logins_total",
    "Number of user logins by method.",
    ["method"],
    namespace=NAMESPACE,
)


class AccountSettingsView(LoginRequiredMixin, BreadcrumbsMixin, UpdateView):
    template_name = "pages/accounts/settings.html"
    model = User
    form_class = PasswordAccountSettingsForm
    success_url = reverse_lazy("accounts:settings")
    breadcrumbs = [(None, "Settings")]

    def get_form_class(self) -> type[BaseAccountSettingsForm]:
        if self.object.password and self.object.has_usable_password():
            return PasswordAccountSettingsForm
        else:
            return TOTPAccountSettingsForm

    def get_object(self, queryset: QuerySet[User] | None = None) -> User:
        assert self.request.user.is_authenticated
        return self.request.user

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.object
        return kwargs

    def form_valid(self, form: BaseAccountSettingsForm) -> HttpResponse:
        self.object = form.save()

        if form.cleaned_data.get("new_password2"):
            messages.success(self.request, "Your password has been changed.")
            # Award Crypt Keeper
            award_builtin_basic_achievement("a3db72f7-6f7a-4f27-8996-ae1006df4b0d", self.object)

            # Cycle sessions if password has changed
            update_session_auth_hash(self.request, self.object)
        else:
            messages.success(self.request, "Updated account successfully.")

            # Award Identity Upgrade
            award_builtin_basic_achievement("a5927f71-f60a-4d7b-9abe-7427bf617dac", self.object)
        return redirect(self.get_success_url())

    def get_context_data(self, **kwargs: Any) -> dict[Any, Any]:
        assert self.request.user.is_authenticated
        return super().get_context_data(
            badges=self.request.user.badges.all(),
            **kwargs,
        )


class LoginLandingView(LoginPageMixin, BreadcrumbsMixin, TemplateView):
    template_name = "pages/accounts/login_landing.html"
    breadcrumbs = [(None, "Login to GCHQ.NET")]


class CredentialsLoginView(LoginPageMixin, BreadcrumbsMixin, DjangoLoginView):
    template_name = "pages/accounts/login_credentials.html"
    form_class = CredentialsLoginForm
    breadcrumbs = [(reverse_lazy("accounts:login"), "Login to GCHQ.NET"), (None, "Login using your password")]

    def form_valid(self, form: AuthenticationForm) -> HttpResponse:
        logins_counter.labels("password").inc()
        return super().form_valid(form)


class BadgeLoginLandingView(LoginPageMixin, BreadcrumbsMixin, TemplateView):
    template_name = "pages/accounts/login_badge_landing.html"
    breadcrumbs = [(reverse_lazy("accounts:login"), "Login to GCHQ.NET"), (None, "Login using your badge")]


class BadgeLoginUsernamePromptView(LoginPageMixin, BreadcrumbsMixin, FormView):
    template_name = "pages/accounts/login_badge_username.html"
    form_class = BadgeLoginUsernameForm
    success_url = reverse_lazy("accounts:login_badge_challenge")
    breadcrumbs = [(reverse_lazy("accounts:login"), "Login to GCHQ.NET"), (None, "Login using your badge")]

    def form_valid(self, form: BadgeLoginUsernameForm) -> HttpResponse:
        self.request.session["badge_login__user_id"] = form.cleaned_data["account_name"].id
        resp = super().form_valid(form)
        if next_q := self.request.GET.get("next"):
            resp["Location"] += f"?next={next_q}"
        return resp


class BadgeLoginChallengePromptView(LoginPageMixin, RedirectURLMixin, BreadcrumbsMixin, FormView):
    template_name = "pages/accounts/login_badge_challenge.html"
    form_class = BadgeLoginChallengeForm
    breadcrumbs = [(reverse_lazy("accounts:login"), "Login to GCHQ.NET"), (None, "Login using your badge")]

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if "badge_login__user_id" not in request.session:
            return redirect("accounts:login_badge")
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()

        # We might see a 500 here sometimes, but that's okay.
        user_id = self.request.session.get("badge_login__user_id", -1)
        kwargs["user"] = User.objects.get(id=user_id, is_active=True)
        return kwargs

    def form_valid(self, form: BadgeLoginChallengeForm) -> HttpResponse:
        del self.request.session["badge_login__user_id"]
        if form.user.is_superuser:
            messages.info(self.request, "Please login with a password for security purposes.")
            return redirect("accounts:login_credentials")
        else:
            # Award beyond the badge
            award_builtin_basic_achievement("145047b2-697b-4ce9-9f2d-b3ef03c2e507", form.user)
            logins_counter.labels("otp").inc()
            auth_login(self.request, form.user)
            return super().form_valid(form)

    def get_default_redirect_url(self) -> str:
        """Return the default redirect URL."""
        if self.next_page:
            return resolve_url(self.next_page)
        else:
            return resolve_url(settings.LOGIN_REDIRECT_URL)

gchqnet/achievements/api/views.py
from uuid import UUID

from django.conf import settings
from django.core.signing import BadSignature, Signer
from django.shortcuts import get_object_or_404
from drf_spectacular.utils import extend_schema
from rest_framework import exceptions, permissions, serializers, viewsets
from rest_framework.decorators import action
from rest_framework.request import Request
from rest_framework.response import Response

from gchqnet.accounts.models.user import User
from gchqnet.achievements.models import BasicAchievement, BasicAchievementAwardType
from gchqnet.achievements.repository import award_builtin_basic_achievement

from .serializers import AchievementSubmissionSerializer


class AchievementViewset(viewsets.GenericViewSet):
    permission_classes = (permissions.AllowAny,)

    @extend_schema(
        summary="Submit an achievement gained on another server",
        exclude=settings.HIDE_PRIVATE_API_ENDPOINTS,
        request=AchievementSubmissionSerializer,
        responses={200: serializers.Serializer, 201: serializers.Serializer},
        tags=["Achievements"],
    )
    @action(methods=["POST"], detail=True)
    def submit(self, request: Request, pk: UUID) -> Response:
        serializer = AchievementSubmissionSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        achievement = get_object_or_404(BasicAchievement, pk=pk)

        if achievement.award_type != BasicAchievementAwardType.EXTERNAL:
            raise exceptions.ValidationError(
                detail={"detail": ["That achievement cannot be awarded using this endpoint."]}
            )

        signer = Signer()

        try:
            obj = signer.unsign_object(serializer.validated_data["token"])
        except BadSignature:
            raise exceptions.AuthenticationFailed() from None

        if str(achievement.id) != obj["ba"]:
            raise exceptions.ValidationError(detail={"detail": ["That token isn't allowed to award that achievement"]})

        try:
            user = User.objects.get(username=serializer.validated_data["username"])
        except User.DoesNotExist:
            raise exceptions.ValidationError(detail={"detail": ["That user cannot be found."]}) from None

        result = award_builtin_basic_achievement(achievement.id, user)

        resp_code_lut = {"success": 201, "already_obtained": 200, "failure": 500}

        return Response(status=resp_code_lut[result])

gchqnet/content/views.py
from django.views.generic import TemplateView

from gchqnet.core.mixins import BreadcrumbsMixin


class AboutPage(BreadcrumbsMixin, TemplateView):
    template_name = "pages/content/about.html"
    breadcrumbs = [(None, "About GCHQ.NET")]


class ContactPage(BreadcrumbsMixin, TemplateView):
    template_name = "pages/content/contact.html"
    breadcrumbs = [(None, "Contact Us")]
    extra_context = {"dect_number": "4247", "fax_number": "2999"}


class PlayPage(BreadcrumbsMixin, TemplateView):
    template_name = "pages/content/play.html"
    breadcrumbs = [(None, "How to Play")]


class PlatformsPage(BreadcrumbsMixin, TemplateView):
    template_name = "pages/content/platforms.html"
    breadcrumbs = [(None, "Our Platforms")]


class HoldingPage(TemplateView):
    template_name = "pages/content/holding.html"

gchqnet/templates/components/govuk/breadcrumbs.html
{% if breadcrumbs %}
    <div class="govuk-breadcrumbs">
        <ol class="govuk-breadcrumbs__list">
            {% for url, name in breadcrumbs %}
                <li class="govuk-breadcrumbs__list-item">
                    {% if url %}
                        <a class="govuk-breadcrumbs__link" href="{{ url }}">{{ name }}</a>
                    {% else %}
                        {{ name }}
                    {% endif %}
                </li>
            {% endfor %}
        </ol>
    </div>
{% endif %}

gchqnet/templates/components/govuk/cookie-banner.html
<form action="/form-handler" method="post" novalidate>
  <div class="govuk-cookie-banner" data-nosnippet role="region" aria-label="Cookies on [name of service]">
    <div class="govuk-cookie-banner__message govuk-width-container">
      <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
          <h2 class="govuk-cookie-banner__heading govuk-heading-m">
            Cookies on Great Camp Hexpansion Quest
          </h2>
          <div class="govuk-cookie-banner__content">
            <p class="govuk-body">We use some essential cookies to make this service work.</p>
            <p class="govuk-body">We’d also like to use analytics cookies so we can understand how you use the service and make improvements.</p>
          </div>
        </div>
      </div>
      <div class="govuk-button-group">
        <button value="yes" type="submit" name="cookies[analytics]" class="govuk-button" data-module="govuk-button">
          Accept analytics cookies
        </button>
        <button value="no" type="submit" name="cookies[analytics]" class="govuk-button" data-module="govuk-button">
          Reject analytics cookies
        </button>
        <a class="govuk-link" href="#">View cookies</a>
      </div>
    </div>
  </div>
</form>

gchqnet/templates/components/govuk/footer.html
{% load static %}
<footer class="govuk-footer">
  <div class="govuk-width-container">
    <div class="govuk-footer__meta">
      <div class="govuk-footer__meta-item govuk-footer__meta-item--grow">
        {% if GAME_MODE != "holding" or request.user.is_authenticated %}
          <h2 class="govuk-visually-hidden">Support links</h2>
          <ul class="govuk-footer__inline-list">
            <li class="govuk-footer__inline-list-item">
              <a class="govuk-footer__link" href="{% url 'content:about' %}">
                About
              </a>
            </li>
            <li class="govuk-footer__inline-list-item">
              <a class="govuk-footer__link" href="{% url 'content:platforms' %}">
                Platforms
              </a>
            </li>
            <li class="govuk-footer__inline-list-item">
              <a class="govuk-footer__link" href="{% url 'api:docs' %}">
                API
              </a>
            </li>
            <li class="govuk-footer__inline-list-item">
              <a class="govuk-footer__link" href="{% url 'content:contact' %}">
                Contact
              </a>
            </li>
	    <!--
            <li class="govuk-footer__inline-list-item">
              <a class="govuk-footer__link" href="#">
                Terms and conditions
              </a>
            </li>
	    -->
          </ul>
        {% endif %}
        <p class="govuk-body-xs">
          <em>GCHQ.NET</em>&nbsp;is not associated with the UK Government or any entity associated with the UK Government.
        </p>
        <p class="govuk-body-xs">
          Kindly hosted by <a class="govuk-link govuk-link--muted govuk-link--no-underline" href="https://www.mythic-beasts.com/">Mythic Beasts</a>.
        </p>
      </div>
    </div>
  </div>
</footer>

gchqnet/templates/components/govuk/header.html
{% load static %}
<header class="govuk-header" data-module="govuk-header">
    <div class="govuk-header__container govuk-width-container">
        <div class="govuk-header__logo">
            <a href="{% url 'quest:home' %}" class="govuk-header__link govuk-header__link--homepage">
                <img src="{% static 'img/logo-white-notext.png' %}" class="gchqnet-header__logo" alt="GCHQ.NET Logo" />
                <span class="gchqnet-header__logotext">GCHQ.NET</span>
            </a>
        </div>
        {% if GAME_MODE != "holding" or request.user.is_authenticated %}
            <div class="govuk-header__content">
                <a href="{% url 'quest:home' %}" class="govuk-header__link govuk-header__service-name">
                    Great Camp Hexpansion Quest
                </a>
                <nav aria-label="Menu" class="govuk-header__navigation">
                    <button type="button" class="govuk-header__menu-button govuk-js-header-toggle" aria-controls="navigation" hidden>
                        Menu
                    </button>
                    {% with view=request.resolver_match.view_name %}
                        <ul id="navigation" class="govuk-header__navigation-list">
                            {% if GAME_MODE != "post" %}
                                <li class="govuk-header__navigation-item {% if view == "quest:home" %}govuk-header__navigation-item--active{% endif %}">
                                    <a class="govuk-header__link" href="{% url 'quest:home' %}">
                                        Live Scores
                                    </a>
                                </li>
                            {% else %}
                                <li class="govuk-header__navigation-item {% if view == "quest:global-scoreboard" %}govuk-header__navigation-item--active{% endif %}">
                                    <a class="govuk-header__link" href="{% url 'quest:global-scoreboard' %}">
                                        Scores
                                    </a>
                                </li>
                            {% endif %}
                            <li class="govuk-header__navigation-item {% if view == "content:play" %}govuk-header__navigation-item--active{% endif %}">
                                <a class="govuk-header__link" href="{% url 'content:play' %}">
                                    How to Play
                                </a>
                            </li>
                            <li class="govuk-header__navigation-item {% if view == "quest:profile" %}govuk-header__navigation-item--active{% endif %}">
                                <a class="govuk-header__link" href="{% url 'quest:profile' %}">
                                    My Profile
                                </a>
                            </li>
                            <li class="govuk-header__navigation-item {% if view == "quest:leaderboard_list" %}govuk-header__navigation-item--active{% endif %}">
                                <a class="govuk-header__link" href="{% url 'quest:leaderboard_list' %}">
                                    My Leaderboards
                                </a>
                            </li>
                            {% if request.user.is_authenticated %}
                                <li class="govuk-header__navigation-item">
                                    <a class="govuk-header__link" href="{% url 'accounts:settings' %}">
                                        Settings
                                    </a>
                                </li>
                            {% endif %}
                            {% if request.user.is_superuser %}
                                <li class="govuk-header__navigation-item {% if view == 'logistics:home' %}govuk-header__navigation-item--active{% endif %}">
                                    <a class="govuk-header__link" href="{% url 'logistics:home' %}">
                                        Admin
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    {% endwith %}
                </nav>
            </div>
        {% endif %}
    </div>
</header>

gchqnet/templates/components/govuk/notification-banner.html
<div class="govuk-notification-banner govuk-notification-banner--{{ variant|default:"info" }}" role="alert" aria-labelledby="govuk-notification-banner-title" data-module="govuk-notification-banner">
  <div class="govuk-notification-banner__header">
    <h2 class="govuk-notification-banner__title" id="govuk-notification-banner-title">
      {{ title|default:"Info" }}
    </h2>
  </div>
  <div class="govuk-notification-banner__content">
    <h3 class="govuk-notification-banner__heading">
      {{ heading }}
    </h3>
    {% if description %}
      <p class="govuk-body">{{ description }}</p>
    {% endif %}
  </div>
</div>

gchqnet/templates/components/govuk/pagination.html
<nav class="govuk-pagination {{ extra_classes}}" aria-label="Pagination">
  {% if page_obj.has_previous %}
    <div class="govuk-pagination__prev">
      <a class="govuk-link govuk-pagination__link" href="?page={{ page_obj.previous_page_number }}" rel="prev">
        <svg class="govuk-pagination__icon govuk-pagination__icon--prev" xmlns="http://www.w3.org/2000/svg" height="13" width="15" aria-hidden="true" focusable="false" viewBox="0 0 15 13">
          <path d="m6.5938-0.0078125-6.7266 6.7266 6.7441 6.4062 1.377-1.449-4.1856-3.9768h12.896v-2h-12.984l4.2931-4.293-1.414-1.414z"></path>
        </svg>
        <span class="govuk-pagination__link-title">
          Previous<span class="govuk-visually-hidden"> page</span>
        </span>
      </a>
    </div>
  {% endif %}
  <ul class="govuk-pagination__list">
    {% for i in page_obj.paginator.page_range %}
      {% if i <= page_obj.number|add:5 and i >= page_obj.number|add:-5 %}
        <li class="govuk-pagination__item {% if i == page_obj.number %}govuk-pagination__item--current{% endif %}">
          <a class="govuk-link govuk-pagination__link" href="?page={{ i }}" aria-label="Page {{ i }}">
            {{i}}
          </a>
        </li>
      {% endif %}
    {% endfor %}
  </ul>
  {% if page_obj.has_next %}
    <div class="govuk-pagination__next">
      <a class="govuk-link govuk-pagination__link" href="?page={{ page_obj.next_page_number }}" rel="next">
        <span class="govuk-pagination__link-title">
          Next<span class="govuk-visually-hidden"> page</span>
        </span>
        <svg class="govuk-pagination__icon govuk-pagination__icon--next" xmlns="http://www.w3.org/2000/svg" height="13" width="15" aria-hidden="true" focusable="false" viewBox="0 0 15 13">
          <path d="m8.107-0.0078125-1.4136 1.414 4.2926 4.293h-12.986v2h12.896l-4.1855 3.9766 1.377 1.4492 6.7441-6.4062-6.7246-6.7266z"></path>
        </svg>
      </a>
    </div>
  {% endif %}
</nav>

gchqnet/templates/components/govuk/phase-banner.html
{% load notifications_tags %}
<div class="govuk-phase-banner">
    <p class="govuk-phase-banner__content">
        <strong class="govuk-tag govuk-phase-banner__content__tag">
            Beta
        </strong>
        <span class="govuk-phase-banner__text gchqnet-phase-banner__text">
            {% if request.user.is_authenticated %}
                <span class="gchqnet-phase-banner__login-status">
                    <span>Hi, <strong>{{ request.user.display_name }}</strong></span>
                    <span>|</span>
                    <a class="govuk-link" href="{% url 'notifications:unread' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
                            <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2m.995-14.901a1 1 0 1 0-1.99 0A5 5 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901"/>
                        </svg>
                        <span class="govuk-visually-hidden">Notifications</span>
                        ({% notifications_unread %})</a>
                    <span>|</span>
                    <span><strong>Score:</strong>&nbsp;{{ request.user.get_current_score }}</span>
                    <span>|</span>
                    <a class="govuk-link" href="#logout" onclick="document.getElementById('logoutForm').submit(); return false;">
                        Logout
                    </a>
                </span>
            {% else %}
                <span class="gchqnet-phase-banner__service-info">This is a new service – your <a class="govuk-link" href="https://youtu.be/dQw4w9WgXcQ">feedback</a> will help us to improve it.</span>
                {% if GAME_MODE != "holding" %}
                    <span class="gchqnet-phase-banner__login-status">
                        <a class="govuk-link" href="{% url 'accounts:login' %}">
                            Login
                        </a>
                    </span>
                {% endif %}
            {% endif %}
        </span>
    </p>
</div>
<form id="logoutForm" method="post" action="{% url 'accounts:logout' %}">
    {% csrf_token %}
</form>

gchqnet/templates/components/govuk/tag.html
<strong class="govuk-tag{% if colour %} govuk-tag--{{colour}}{% endif %}">
    {{ content }}
</strong>

gchqnet/templates/components/govuk/warning-text.html
<div class="govuk-warning-text">
  <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
  <strong class="govuk-warning-text__text">
    <span class="govuk-visually-hidden">Warning</span>
    {{ warning_text}}
  </strong>
</div>